### PR TITLE
fix: missing TLS ServerName

### LINKED ISSUE #51: Handle ServerName with TLS
This might cause an issue:
https://github.com/cloud-gouv/portail/blob/fa0c9593ffd1e3956bf7c708291afb6b8e8133e4/src/proxy/http_connect.rs#L205-L206

- [ ] add another vhost to the E2E test to check that SNI works

### PR DESCRIPTION
**Pull request by agrimault-dinum**
Fixes #51 

First commit e522d8332b45329c75c8cccce7c9482cdb57da3b shows the bug with a failing test:
`portail::proxy::http_connect: Backend 192.168.1.3:8080 failed for HTTP CONNECT: invalid peer certificate: certificate not valid for name "192.168.1.3"; certificate is only valid for DnsName("portail.corp.example.com"), trying next`

### CODE REVIEW

**Review by rlahfa-dinum — APPROVED** [review]
Nitpick: make `tls_server_name: Option<ServerName>` perhaps, this would be interesting.

File: src/config.rs [hunk 1]
```diff
@@ -5,15 +5,69 @@ use std::{
...
     pub identity_aware: bool,
+    /// TLS server name for identity-aware outbound connections.
+    ///
+    /// When omitted in config, the target address IP is used.
+    pub tls_server_name: ServerName<'static>,
+}
+
+#[derive(Debug, Deserialize, Serialize)]
+#[serde(rename_all = "kebab-case")]
+struct BackendSettingsSerde {
```
Comment (rlahfa-dinum) [inline src/config.rs]: nitpick: je l'appellerais `raw` perso

**Review by rlahfa-dinum — APPROVED** [review]
